#!/usr/bin/env sh

UNAME=$(uname)
NVIM=${NVIM-nvim}

mkdir -p ~/.config/nvim/colors ~/.config/nvim/syntax
cp init.vim ~/.config/nvim
cp newdefault.vim ~/.config/nvim/colors/newdefault.vim
cp -r ./syntax/* ~/.config/nvim/syntax/
$NVIM +'PlugInstall --sync' +qa
