#!/usr/bin/env sh

UNAME=$(uname)
NVIM=${NVIM-nvim}

mkdir -p ~/.config/nvim/colors ~/.config/nvim/syntax
cp init.vim ~/.config/nvim
cp newdefault.vim ~/.config/nvim/colors/newdefault.vim
cp -r ./syntax/* ~/.config/nvim/syntax/
cp tmux.conf ~/.tmux.conf

if [ -e ~/.bashrc ]; then
  if grep -q 'alias open="xdg-open"' ~/.bashrc; then
    echo "bashrc already configured, make sure it matches"
  else
    cat bashrc >> ~/.bashrc
  fi
else
  cp bashrc ~/.bashrc
fi

$NVIM +'PlugInstall --sync' +qa
