#!/usr/bin/env sh

UNAME=$(uname)
VIM=${VIM-vim}
NVIM=${NVIM-nvim}

case $UNAME in
    *BSD)
        MAKE=gmake
        ;;
    *)
        MAKE=make
        ;;
esac

case $1 in
    vim)
        mkdir -p ~/.vim
        cp init.vim ~/.vimrc
        $VIM +'PlugInstall --sync' +qa
        if [ ! -f ~/.vim/plugged/clang_complete/.modified ]; then
            sed -i "s/vim/$VIM/g" ~/.vim/plugged/clang_complete/Makefile
            touch ~/.vim/plugged/clang_complete/.modified
        fi
        cd ~/.vim/plugged/clang_complete && \
            $MAKE && \
            $MAKE install
        ;;
    nvim|neovim)
        mkdir -p ~/.config/nvim
        cp init.vim ~/.config/nvim
        $NVIM +'PlugInstall --sync' +qa
        if [ ! -f ~/.config/nvim/plugged/clang_complete/.modified ]; then
            sed -i "s/vim/$NVIM/g" ~/.config/nvim/plugged/clang_complete/Makefile
            touch ~/.config/nvim/plugged/clang_complete/.modified
        fi
        cd ~/.config/nvim/plugged/clang_complete && \
            $MAKE && \
            $MAKE install
        ;;
    all|both)
        $0 vim
        $0 neovim
        ;;
    *)
        echo "Invalid vim executable name"
        ;;
esac
